#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract Fig. 4 throughput data.

The extraction intentionally avoids case_id/case_plan matching. SmallBank rows
are selected by workload parameters, and TPC-C rows are selected by result
folder names and run modes.
"""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path
from pprint import pformat


REVISON_DRAW_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = Path(__file__).resolve().parents[4]

DEFAULT_SMALLBANK_DIR = PROJECT_ROOT / "vldb_res" / "20260709000616(main)"
DEFAULT_TPCC_DIR = PROJECT_ROOT / "vldb_res" / "20260716015113(tpcc-200)"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fig4_overall.py"

SYSTEMS = [
    ("RR", "0"),
    ("MWR", "25"),
    ("PHR", "2"),
    ("PAR", "23"),
    ("CPR", "28"),
    ("MP-Router", "11"),
]

SMALLBANK_THETAS = [
    ("0.1", "access"),
    ("0.6", "access"),
    ("0.8", "base"),
    ("0.9", "access"),
    ("1.1", "access"),
]

TPCC_GROUPS = [
    ("Normal", "tpcc-standard_p0_wh200_t16_r0.8_b10000_n4_nb1_whpart0_kp1.1_mlp0"),
    ("50%", "tpcc-standard_p2_HsFrac0.25_HsProb0.5_wh200_t16_r0.8_b10000_n4_nb1_whpart0_kp1.1_mlp0"),
    ("80%", "tpcc-standard_p2_HsFrac0.25_HsProb0.8_wh200_t16_r0.8_b10000_n4_nb1_whpart0_kp1.1_mlp0"),
    ("90%", "tpcc-standard_p2_HsFrac0.25_HsProb0.9_wh200_t16_r0.8_b10000_n4_nb1_whpart0_kp1.1_mlp0"),
]


def norm(value: str | None) -> str:
    if value is None:
        return ""
    if value == "":
        return ""
    try:
        return f"{float(value):g}"
    except ValueError:
        return value


def read_summary(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def find_one(rows: list[dict[str, str]], desc: str, **conds: str) -> dict[str, str]:
    matches = []
    for row in rows:
        if all(norm(row.get(key)) == str(expected) for key, expected in conds.items()):
            matches.append(row)
    if len(matches) != 1:
        details = [
            {
                "run_mode": row.get("run_mode"),
                "scan_axis": row.get("scan_axis"),
                "access_pattern": row.get("access_pattern"),
                "zipfian_theta": row.get("zipfian_theta"),
                "worker_threads": row.get("worker_threads"),
                "batch_size": row.get("batch_size"),
                "key_page_ratio": row.get("key_page_ratio"),
                "throughput_after_warmup_tps": row.get("throughput_after_warmup_tps"),
            }
            for row in matches[:8]
        ]
        raise RuntimeError(
            f"{desc}: expected exactly one match, found {len(matches)}. "
            f"conds={conds}, matches={details}"
        )
    return matches[0]


def throughput_from_row(row: dict[str, str]) -> float:
    return round(float(row["throughput_after_warmup_tps"]), 2)


def extract_smallbank(smallbank_dir: Path) -> list[tuple[str, list[float]]]:
    rows = read_summary(smallbank_dir / "summary.csv")
    data = []
    for theta, scan_axis in SMALLBANK_THETAS:
        values = []
        for _, mode in SYSTEMS:
            row = find_one(
                rows,
                f"SmallBank theta={theta} mode={mode}",
                workload="smallbank",
                scan_axis=scan_axis,
                access_pattern="1",
                zipfian_theta=theta,
                zipfian_generator="finite",
                worker_threads="16",
                affinity_txn_ratio="0.8",
                batch_size="10000",
                key_page_ratio="1.1",
                mlp_enabled="0",
                run_mode=mode,
            )
            values.append(throughput_from_row(row))
        data.append((theta, values))
    return data


def read_after_warmup_tps(result_file: Path) -> float:
    text = result_file.read_text(errors="ignore")
    match = re.search(r"Throughput \(after warmup\):\s*([0-9.]+)", text)
    if not match:
        raise RuntimeError(f"Cannot find after-warmup throughput in {result_file}")
    return round(float(match.group(1)), 2)


def extract_tpcc(tpcc_dir: Path) -> list[tuple[str, list[float]]]:
    data = []
    for label, folder in TPCC_GROUPS:
        values = []
        for _, mode in SYSTEMS:
            result_file = tpcc_dir / folder / f"m{mode}" / "result.txt"
            if not result_file.exists():
                raise FileNotFoundError(result_file)
            values.append(read_after_warmup_tps(result_file))
        data.append((label, values))
    return data


def write_module(
    output: Path,
    smallbank_dir: Path,
    tpcc_dir: Path,
    smallbank_data: list[tuple[str, list[float]]],
    tpcc_data: list[tuple[str, list[float]]],
) -> None:
    system_names = [name for name, _ in SYSTEMS]
    lines = [
        "# Auto-generated by extract_fig4_overall.py.",
        "# Do not edit by hand; rerun the extractor with the intended data directories.",
        "#",
        f"# SmallBank source: {smallbank_dir}",
        f"# TPC-C source: {tpcc_dir}",
        "",
        f"MAIN_SYSTEMS = {pformat(system_names, width=120)}",
        "",
        "TPCC_SYSTEMS = MAIN_SYSTEMS",
        "",
        f"throughput_zipfian_data = {pformat(smallbank_data, width=120)}",
        "",
        f"tpcc_data = {pformat(tpcc_data, width=120)}",
        "",
        "MISSING = []",
        "",
        "WARNINGS = []",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--smallbank-dir", type=Path, default=DEFAULT_SMALLBANK_DIR)
    parser.add_argument("--tpcc-dir", type=Path, default=DEFAULT_TPCC_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    smallbank_data = extract_smallbank(args.smallbank_dir)
    tpcc_data = extract_tpcc(args.tpcc_dir)
    write_module(args.output, args.smallbank_dir, args.tpcc_dir, smallbank_data, tpcc_data)

    print(f"Wrote {args.output}")
    print(f"SmallBank source: {args.smallbank_dir}")
    print(f"TPC-C source: {args.tpcc_dir}")


if __name__ == "__main__":
    main()
