#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract Fig. 8 thread-scalability throughput data from result.txt files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from pprint import pformat


PROJECT_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_MAIN_DIR = PROJECT_ROOT / "vldb_res" / "20260709000616(main)"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fig8_thread_scalability.py"

SYSTEMS = [
    ("RR", "0"),
    ("MWR", "25"),
    ("PHR", "2"),
    ("PAR", "23"),
    ("CPR", "28"),
    ("MP-Router", "11"),
]

THREAD_COUNTS = ["2", "4", "8", "16", "24", "32"]

SMALLBANK_TEMPLATES = (
    "smallbank_p1_ZipfTheta0.8_ZipfGenfinite_acc10000000"
    "_t{threads}_r0.8_b10000_nb1_whpart0_kp1.1_mlp0",
    "smallbank_p1_ZipfTheta0.8_ZipfGenfinite_acc10000000"
    "_t{threads}_r0.8_b10000_n4_nb1_whpart0_kp1.1_mlp0",
)


def read_after_warmup_tps(result_file: Path) -> float:
    text = result_file.read_text(errors="ignore")
    match = re.search(r"Throughput \(after warmup\):\s*([0-9.]+)", text)
    if not match:
        raise RuntimeError(f"Cannot find after-warmup throughput in {result_file}")
    return round(float(match.group(1)), 2)


def result_path(root: Path, threads: str, mode: str) -> Path:
    matches = []
    for template in SMALLBANK_TEMPLATES:
        folder = template.format(threads=threads)
        path = root / folder / f"m{mode}" / "result.txt"
        if path.exists():
            matches.append(path)
    if len(matches) != 1:
        raise RuntimeError(
            f"threads={threads}, mode={mode}: expected exactly one result, "
            f"found {len(matches)} under {root}. matches={matches}"
        )
    return matches[0]


def extract_thread_scalability(main_dir: Path) -> list[tuple[str, list[float]]]:
    data = []
    for threads in THREAD_COUNTS:
        values = []
        for _, mode in SYSTEMS:
            values.append(read_after_warmup_tps(result_path(main_dir, threads, mode)))
        data.append((threads, values))
    return data


def write_module(output: Path, main_dir: Path, data: list[tuple[str, list[float]]]) -> None:
    system_names = [name for name, _ in SYSTEMS]
    lines = [
        "# Auto-generated by extract_fig8_thread_scalability.py.",
        "# Do not edit by hand; rerun the extractor with the intended data directory.",
        "#",
        f"# Thread-scalability source: {main_dir}",
        "",
        f"MAIN_SYSTEMS = {pformat(system_names, width=120)}",
        "",
        f"thread_scalability_data = {pformat(data, width=120)}",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--main-dir", type=Path, default=DEFAULT_MAIN_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    data = extract_thread_scalability(args.main_dir)
    write_module(args.output, args.main_dir, data)

    print(f"Wrote {args.output}")
    print(f"Thread-scalability source: {args.main_dir}")


if __name__ == "__main__":
    main()
