#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract Fig. 12 key-page-map capacity data from result.txt files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from pprint import pformat


PROJECT_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_MAIN_DIR = PROJECT_ROOT / "vldb_res" / "20260709000616(main)"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fig12_key_page_map.py"

SYSTEMS = [
    ("PHR", "2"),
    ("PAR", "23"),
    ("CPR", "28"),
    ("MP-Router", "11"),
]

KEY_PAGE_RATIOS = [
    ("20%", "0.2"),
    ("40%", "0.4"),
    ("60%", "0.6"),
    ("80%", "0.8"),
    ("100%", "1.0"),
]

SMALLBANK_TEMPLATE = (
    "smallbank_p1_ZipfTheta0.8_ZipfGenfinite_acc10000000"
    "_t16_r0.8_b10000_nb1_whpart0_kp{ratio}_mlp0"
)


def read_after_warmup_tps(result_file: Path) -> float:
    text = result_file.read_text(errors="ignore")
    match = re.search(r"Throughput \(after warmup\):\s*([0-9.]+)", text)
    if not match:
        raise RuntimeError(f"Cannot find after-warmup throughput in {result_file}")
    return round(float(match.group(1)), 2)


def result_path(root: Path, ratio: str, mode: str) -> Path:
    folder = SMALLBANK_TEMPLATE.format(ratio=ratio)
    path = root / folder / f"m{mode}" / "result.txt"
    if not path.exists():
        raise FileNotFoundError(path)
    return path


def extract_key_page_map(main_dir: Path) -> list[tuple[str, list[float]]]:
    data = []
    for label, ratio in KEY_PAGE_RATIOS:
        values = []
        for _, mode in SYSTEMS:
            values.append(read_after_warmup_tps(result_path(main_dir, ratio, mode)))
        data.append((label, values))
    return data


def write_module(output: Path, main_dir: Path, data: list[tuple[str, list[float]]]) -> None:
    system_names = [name for name, _ in SYSTEMS]
    lines = [
        "# Auto-generated by extract_fig12_key_page_map.py.",
        "# Do not edit by hand; rerun the extractor with the intended data directory.",
        "#",
        f"# Key-page-map source: {main_dir}",
        "",
        f"KP_SYSTEMS = {pformat(system_names, width=120)}",
        "",
        f"key_page_map_data = {pformat(data, width=120)}",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--main-dir", type=Path, default=DEFAULT_MAIN_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    data = extract_key_page_map(args.main_dir)
    write_module(args.output, args.main_dir, data)

    print(f"Wrote {args.output}")
    print(f"Key-page-map source: {args.main_dir}")


if __name__ == "__main__":
    main()
