#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract Fig. 10 transaction-window-size throughput data from result.txt files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from pprint import pformat


PROJECT_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_BATCH_DIR = PROJECT_ROOT / "vldb_res" / "20260717100527(batch-size)"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fig10_batch_size.py"

BATCH_SIZES = ["10", "50", "100", "1000", "10000", "100000"]
RUN_MODE = "11"

SMALLBANK_TEMPLATE = (
    "smallbank_p1_ZipfTheta0.8_ZipfGenfinite_acc10000000"
    "_t16_r0.8_b{batch_size}_n4_nb1_whpart0_kp1.1_mlp0"
)


def read_after_warmup_tps(result_file: Path) -> float:
    text = result_file.read_text(errors="ignore")
    match = re.search(r"Throughput \(after warmup\):\s*([0-9.]+)", text)
    if not match:
        raise RuntimeError(f"Cannot find after-warmup throughput in {result_file}")
    return round(float(match.group(1)), 2)


def result_path(root: Path, batch_size: str) -> Path:
    folder = SMALLBANK_TEMPLATE.format(batch_size=batch_size)
    path = root / folder / f"m{RUN_MODE}" / "result.txt"
    if not path.exists():
        raise FileNotFoundError(path)
    return path


def extract_batch_size(batch_dir: Path) -> list[tuple[str, float]]:
    return [
        (batch_size, read_after_warmup_tps(result_path(batch_dir, batch_size)))
        for batch_size in BATCH_SIZES
    ]


def write_module(output: Path, batch_dir: Path, data: list[tuple[str, float]]) -> None:
    lines = [
        "# Auto-generated by extract_fig10_batch_size.py.",
        "# Do not edit by hand; rerun the extractor with the intended data directory.",
        "#",
        f"# Batch-size source: {batch_dir}",
        "",
        f"batch_size_data = {pformat(data, width=120)}",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--batch-dir", type=Path, default=DEFAULT_BATCH_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    data = extract_batch_size(args.batch_dir)
    write_module(args.output, args.batch_dir, data)

    print(f"Wrote {args.output}")
    print(f"Batch-size source: {args.batch_dir}")


if __name__ == "__main__":
    main()
