#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract Fig. 9 node-scalability throughput data from result.txt files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from pprint import pformat


PROJECT_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_NODE_DIR = PROJECT_ROOT / "vldb_res" / "20260718005118(8-node)"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fig9_node_scalability.py"

SYSTEMS = [
    ("RR", "0"),
    ("MWR", "25"),
    ("PHR", "2"),
    ("PAR", "23"),
    ("CPR", "28"),
    ("MP-Router", "11"),
]

NODE_COUNTS = ["1", "2", "3", "4", "5", "6", "7", "8"]

SMALLBANK_TEMPLATE = (
    "smallbank_p1_ZipfTheta0.8_ZipfGenfinite_acc10000000"
    "_t16_r0.8_b10000_n{nodes}_nb1_whpart0_kp1.1_mlp0"
)


def read_after_warmup_tps(result_file: Path) -> float:
    text = result_file.read_text(errors="ignore")
    match = re.search(r"Throughput \(after warmup\):\s*([0-9.]+)", text)
    if not match:
        raise RuntimeError(f"Cannot find after-warmup throughput in {result_file}")
    return round(float(match.group(1)), 2)


def result_path(root: Path, nodes: str, mode: str) -> Path:
    folder = SMALLBANK_TEMPLATE.format(nodes=nodes)
    path = root / folder / f"m{mode}" / "result.txt"
    if not path.exists():
        raise FileNotFoundError(path)
    return path


def extract_node_scalability(node_dir: Path) -> list[tuple[str, list[float]]]:
    data = []
    for nodes in NODE_COUNTS:
        values = []
        for _, mode in SYSTEMS:
            values.append(read_after_warmup_tps(result_path(node_dir, nodes, mode)))
        data.append((nodes, values))
    return data


def write_module(output: Path, node_dir: Path, data: list[tuple[str, list[float]]]) -> None:
    system_names = [name for name, _ in SYSTEMS]
    lines = [
        "# Auto-generated by extract_fig9_node_scalability.py.",
        "# Do not edit by hand; rerun the extractor with the intended data directory.",
        "#",
        f"# Node-scalability source: {node_dir}",
        "",
        f"MAIN_SYSTEMS = {pformat(system_names, width=120)}",
        "",
        f"node_scalability_data = {pformat(data, width=120)}",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--node-dir", type=Path, default=DEFAULT_NODE_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    data = extract_node_scalability(args.node_dir)
    write_module(args.output, args.node_dir, data)

    print(f"Wrote {args.output}")
    print(f"Node-scalability source: {args.node_dir}")


if __name__ == "__main__":
    main()
