#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract Fig. 7 uniform-hotspot throughput data from result.txt files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from pprint import pformat


PROJECT_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_MAIN_DIR = PROJECT_ROOT / "vldb_res" / "20260709000616(main)"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fig7_uniform_hotspot.py"

SYSTEMS = [
    ("RR", "0"),
    ("MWR", "25"),
    ("PHR", "2"),
    ("PAR", "23"),
    ("CPR", "28"),
    ("MP-Router", "11"),
]

HOTSPOT_FRACTIONS = [
    ("100%", "1"),
    ("10%", "0.1"),
    ("1%", "0.01"),
    ("0.1%", "0.001"),
]

SMALLBANK_TEMPLATE = (
    "smallbank_p2_HsFrac{fraction}_HsProb0.8_acc10000000"
    "_t16_r0.8_b10000_nb1_whpart0_kp1.1_mlp0"
)


def read_after_warmup_tps(result_file: Path) -> float:
    text = result_file.read_text(errors="ignore")
    match = re.search(r"Throughput \(after warmup\):\s*([0-9.]+)", text)
    if not match:
        raise RuntimeError(f"Cannot find after-warmup throughput in {result_file}")
    return round(float(match.group(1)), 2)


def result_path(root: Path, fraction: str, mode: str) -> Path:
    folder = SMALLBANK_TEMPLATE.format(fraction=fraction)
    path = root / folder / f"m{mode}" / "result.txt"
    if not path.exists():
        raise FileNotFoundError(path)
    return path


def extract_hotspot(main_dir: Path) -> list[tuple[str, list[float]]]:
    data = []
    for label, fraction in HOTSPOT_FRACTIONS:
        values = []
        for _, mode in SYSTEMS:
            values.append(read_after_warmup_tps(result_path(main_dir, fraction, mode)))
        data.append((label, values))
    return data


def write_module(output: Path, main_dir: Path, data: list[tuple[str, list[float]]]) -> None:
    system_names = [name for name, _ in SYSTEMS]
    lines = [
        "# Auto-generated by extract_fig7_uniform_hotspot.py.",
        "# Do not edit by hand; rerun the extractor with the intended data directory.",
        "#",
        f"# Uniform-hotspot source: {main_dir}",
        "",
        f"MAIN_SYSTEMS = {pformat(system_names, width=120)}",
        "",
        f"uniform_hotspot_data = {pformat(data, width=120)}",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--main-dir", type=Path, default=DEFAULT_MAIN_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    data = extract_hotspot(args.main_dir)
    write_module(args.output, args.main_dir, data)

    print(f"Wrote {args.output}")
    print(f"Uniform-hotspot source: {args.main_dir}")


if __name__ == "__main__":
    main()
