#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract MLP comparison data from result.txt files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from pprint import pformat


PROJECT_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_BASELINE_DIR = PROJECT_ROOT / "vldb_res" / "20260709000616(main)"
DEFAULT_MLP_DIR = PROJECT_ROOT / "vldb_res" / "20260716071500(mlp)"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fig13_mlp.py"

THETAS = ["0.1", "0.6", "0.8", "0.9", "1.1"]
SYSTEMS = ["MP-Router with MLP", "MP-Router"]

SMALLBANK_TEMPLATE = (
    "smallbank_p1_ZipfTheta{theta}_ZipfGenfinite_acc10000000"
    "_t16_r0.8_b10000{node_part}_nb1_whpart0_kp1.1_mlp{mlp_enabled}"
)


def read_after_warmup_tps(result_file: Path) -> float:
    text = result_file.read_text(errors="ignore")
    match = re.search(r"Throughput \(after warmup\):\s*([0-9.]+)", text)
    if not match:
        raise RuntimeError(f"Cannot find after-warmup throughput in {result_file}")
    return round(float(match.group(1)), 2)


def result_path(root: Path, theta: str, *, mlp_enabled: int, node_part: str) -> Path:
    folder = SMALLBANK_TEMPLATE.format(
        theta=theta,
        node_part=node_part,
        mlp_enabled=mlp_enabled,
    )
    path = root / folder / "m11" / "result.txt"
    if not path.exists():
        raise FileNotFoundError(path)
    return path


def extract_data(baseline_dir: Path, mlp_dir: Path) -> list[tuple[str, list[float]]]:
    data = []
    for theta in THETAS:
        mlp_tps = read_after_warmup_tps(
            result_path(mlp_dir, theta, mlp_enabled=1, node_part="_n4")
        )
        baseline_tps = read_after_warmup_tps(
            result_path(baseline_dir, theta, mlp_enabled=0, node_part="")
        )
        data.append((theta, [mlp_tps, baseline_tps]))
    return data


def write_module(output: Path, baseline_dir: Path, mlp_dir: Path, data: list[tuple[str, list[float]]]) -> None:
    lines = [
        "# Auto-generated by extract_fig13_mlp.py.",
        "# Do not edit by hand; rerun the extractor with the intended data directories.",
        "#",
        f"# MP-Router baseline source: {baseline_dir}",
        f"# MLP source: {mlp_dir}",
        "",
        f"MLP_SYSTEMS = {pformat(SYSTEMS, width=120)}",
        "",
        f"mlp_data = {pformat(data, width=120)}",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--baseline-dir", type=Path, default=DEFAULT_BASELINE_DIR)
    parser.add_argument("--mlp-dir", type=Path, default=DEFAULT_MLP_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    data = extract_data(args.baseline_dir, args.mlp_dir)
    write_module(args.output, args.baseline_dir, args.mlp_dir, data)

    print(f"Wrote {args.output}")
    print(f"MP-Router baseline source: {args.baseline_dir}")
    print(f"MLP source: {args.mlp_dir}")


if __name__ == "__main__":
    main()
