#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract Fig. 6 affinity-ratio throughput data from result.txt files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from pprint import pformat


PROJECT_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_AFFINITY_DIR = PROJECT_ROOT / "vldb_res" / "20260716102209(affinity)"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fig6_affinity.py"

SYSTEMS = [
    ("RR", "0"),
    ("MWR", "25"),
    ("PHR", "2"),
    ("PAR", "23"),
    ("CPR", "28"),
    ("MP-Router", "11"),
]

AFFINITY_RATIOS = [
    ("0%", "0"),
    ("20%", "0.2"),
    ("40%", "0.4"),
    ("60%", "0.6"),
    ("80%", "0.8"),
    ("100%", "1"),
]

SMALLBANK_TEMPLATE = (
    "smallbank_p1_ZipfTheta0.8_ZipfGenfinite_acc10000000"
    "_t16_r{ratio}_b10000{node_part}_nb1_whpart0_kp1.1_mlp0"
)


def read_after_warmup_tps(result_file: Path) -> float:
    text = result_file.read_text(errors="ignore")
    match = re.search(r"Throughput \(after warmup\):\s*([0-9.]+)", text)
    if not match:
        raise RuntimeError(f"Cannot find after-warmup throughput in {result_file}")
    return round(float(match.group(1)), 2)


def result_path(root: Path, ratio: str, mode: str, node_part: str) -> Path:
    folder = SMALLBANK_TEMPLATE.format(ratio=ratio, node_part=node_part)
    path = root / folder / f"m{mode}" / "result.txt"
    if not path.exists():
        raise FileNotFoundError(path)
    return path


def find_result_path(root: Path, ratio: str, mode: str, node_part: str | None) -> Path:
    if node_part is not None:
        return result_path(root, ratio, mode, node_part)

    matches = []
    for candidate_node_part in ("_n4", ""):
        try:
            matches.append(result_path(root, ratio, mode, candidate_node_part))
        except FileNotFoundError:
            pass
    if len(matches) != 1:
        raise RuntimeError(
            f"ratio={ratio}, mode={mode}: expected exactly one result, "
            f"found {len(matches)} under {root}. matches={matches}"
        )
    return matches[0]


def extract_affinity(affinity_dir: Path, node_part: str | None) -> list[tuple[str, list[float]]]:
    data = []
    for label, ratio in AFFINITY_RATIOS:
        values = []
        for _, mode in SYSTEMS:
            values.append(read_after_warmup_tps(find_result_path(affinity_dir, ratio, mode, node_part)))
        data.append((label, values))
    return data


def write_module(output: Path, affinity_dir: Path, data: list[tuple[str, list[float]]]) -> None:
    system_names = [name for name, _ in SYSTEMS]
    lines = [
        "# Auto-generated by extract_fig6_affinity.py.",
        "# Do not edit by hand; rerun the extractor with the intended data directory.",
        "#",
        f"# Affinity source: {affinity_dir}",
        "",
        f"MAIN_SYSTEMS = {pformat(system_names, width=120)}",
        "",
        f"affinity_data = {pformat(data, width=120)}",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--affinity-dir", type=Path, default=DEFAULT_AFFINITY_DIR)
    parser.add_argument(
        "--node-part",
        choices=["_n4", ""],
        default=None,
        help="Folder-name node suffix. By default, auto-detects either '_n4' or no suffix.",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    data = extract_affinity(args.affinity_dir, args.node_part)
    write_module(args.output, args.affinity_dir, data)

    print(f"Wrote {args.output}")
    print(f"Affinity source: {args.affinity_dir}")


if __name__ == "__main__":
    main()
