#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract Fig. 11 router-only throughput and transaction-mix data."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from pprint import pformat


PROJECT_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_ROUTE_ONLY_DIR = PROJECT_ROOT / "vldb_res" / "20260717234540(route-only)"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fig11_route_only.py"

THETAS = ["0.1", "0.6", "0.8", "0.9", "1.1"]
RUN_MODE = "11"

SMALLBANK_TEMPLATE = (
    "smallbank_p1_ZipfTheta{theta}_ZipfGenfinite_acc10000000"
    "_t4_r0.8_b10000_n4_nb1_whpart0_kp1.1_mlp0_rt16_gt8"
)


def read_text(path: Path) -> str:
    return path.read_text(errors="ignore")


def last_float(text: str, pattern: str, source: Path) -> float:
    matches = re.findall(pattern, text)
    if not matches:
        raise RuntimeError(f"Cannot find pattern {pattern!r} in {source}")
    return round(float(matches[-1]), 2)


def result_path(root: Path, theta: str) -> Path:
    path = root / SMALLBANK_TEMPLATE.format(theta=theta) / f"m{RUN_MODE}" / "result.txt"
    if not path.exists():
        raise FileNotFoundError(path)
    return path


def extract_route_only(root: Path) -> list[tuple[str, float, list[tuple[str, float]], float, float]]:
    data = []
    for theta in THETAS:
        path = result_path(root, theta)
        text = read_text(path)
        throughput = last_float(text, r"Throughput \(after warmup\):\s*([0-9.]+)", path)
        conflict_free = last_float(text, r"Conflict-Free Path Txns:\s*\d+ \(([0-9.]+)% of total\)", path)
        critical = last_float(text, r"Conflicting Critical-Path Txns:\s*\d+ \(([0-9.]+)% of total", path)
        non_critical = last_float(text, r"Conflicting Non-Critical-Path Txns:\s*\d+ \(([0-9.]+)% of total", path)
        conflict_free_capacity = last_float(text, r"Conflict-Free Path Estimated Capacity:\s*([0-9.]+) TPS", path)
        conflicting_capacity = last_float(text, r"Conflict Scheduler Estimated Capacity:\s*([0-9.]+) TPS", path)
        mix = [
            ("Conflict-Free", conflict_free),
            ("Critical", critical),
            ("Non-Critical", non_critical),
        ]
        data.append((theta, throughput, mix, conflict_free_capacity, conflicting_capacity))
    return data


def write_module(output: Path, route_only_dir: Path, data: list[tuple[str, float, list[tuple[str, float]], float, float]]) -> None:
    lines = [
        "# Auto-generated by extract_fig11_route_only.py.",
        "# Do not edit by hand; rerun the extractor with the intended data directory.",
        "#",
        f"# Router-only source: {route_only_dir}",
        "",
        f"route_only_data = {pformat(data, width=120)}",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--route-only-dir", type=Path, default=DEFAULT_ROUTE_ONLY_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    data = extract_route_only(args.route_only_dir)
    write_module(args.output, args.route_only_dir, data)

    print(f"Wrote {args.output}")
    print(f"Router-only source: {args.route_only_dir}")


if __name__ == "__main__":
    main()
