# Auto-generated by extract_fig11_route_only.py.
# Do not edit by hand; rerun the extractor with the intended data directory.
#
# Router-only source: ../../../vldb_res/20260717234540(route-only)

route_only_data = [('0.1', 1123416.04, [('Conflict-Free', 97.8), ('Critical', 0.31), ('Non-Critical', 1.92)], 2462029.24, 519852.47),
 ('0.6', 1125278.72, [('Conflict-Free', 96.58), ('Critical', 0.5), ('Non-Critical', 2.95)], 2451029.88, 604238.85),
 ('0.8', 1120879.57, [('Conflict-Free', 86.0), ('Critical', 3.65), ('Non-Critical', 10.35)], 2220181.31, 1118081.94),
 ('0.9', 1110259.32, [('Conflict-Free', 71.83), ('Critical', 10.67), ('Non-Critical', 17.5)], 2277393.05, 1002101.78),
 ('1.1', 742181.79, [('Conflict-Free', 33.55), ('Critical', 38.87), ('Non-Critical', 27.58)], 2002361.55, 614813.67)]
