# Auto-generated by extract_fig10_batch_size.py.
# Do not edit by hand; rerun the extractor with the intended data directory.
#
# Batch-size source: ../../../vldb_res/20260717100527(batch-size)

batch_size_data = [('10', 17181.36),
 ('50', 85605.35),
 ('100', 94144.37),
 ('1000', 106730.45),
 ('10000', 112085.16),
 ('100000', 113017.43)]
