# Auto-generated by extract_fig15_yashan_phases.py.
# Do not edit by hand; rerun the extractor with the intended result directory.
# Phase means use raw TPS samples, without plot-time resampling.
#
# Source: /Users/hcy/Desktop/Ruc/论文投稿/SIGMOD 2026 MP-Router/vldb_res/20260715020857(yashan)/smallbank_p1_ZipfTheta0.8_ZipfGenfinite_acc10000000_t16_r0.8_b10000_nb1_whpart0_kp1.1_mlp0

SYSTEMS = ['RR', 'MWR', 'PHR', 'PAR', 'CPR', 'MP-Router']

BASELINE_SYSTEMS = ['RR', 'MWR', 'PHR', 'PAR', 'CPR']

TARGET_SYSTEM = 'MP-Router'

SOURCE_INTERVAL_SECONDS = 2.0

PHASE_BOUNDS_MINUTES = [('Warmup', 0.0, 5.0),
 ('Partitioned', 5.0, 10.0),
 ('Low Affinity', 10.0, 15.0),
 ('Change Affinity', 15.0, 20.0),
 ('High Skew', 20.0, 25.0)]

PHASE_DESCRIPTIONS = {'Warmup': 'Initial warmup',
 'Partitioned': 'theta=0.8 and affinity transaction ratio=80%',
 'Low Affinity': 'affinity transaction ratio=20%',
 'Change Affinity': 'restore affinity transaction ratio to 80% and replace about 50% of friend relationships',
 'High Skew': 'theta=0.95'}

phase_throughput_tps = [('Warmup', [993.42, 1337.32, 1499.39, 1086.25, 2202.33, 48982.88]),
 ('Partitioned', [1681.65, 2547.54, 2292.57, 30972.43, 40571.47, 57045.87]),
 ('Low Affinity', [2097.85, 2461.07, 2221.54, 2952.73, 4681.81, 50448.75]),
 ('Change Affinity', [3795.37, 3621.33, 5655.12, 11696.07, 18699.78, 57338.85]),
 ('High Skew', [491.6, 457.75, 692.99, 687.03, 1023.11, 7297.29])]

phase_sample_counts = [('Warmup', [150, 150, 150, 150, 150, 150]),
 ('Partitioned', [150, 150, 150, 150, 150, 150]),
 ('Low Affinity', [150, 150, 150, 150, 150, 150]),
 ('Change Affinity', [150, 150, 150, 150, 150, 150]),
 ('High Skew', [149, 149, 149, 149, 149, 149])]

# Each phase's throughput as a percentage of the same system's Partitioned phase.
retention_vs_partitioned_percent = [('Warmup', [59.07, 52.49, 65.4, 3.51, 5.43, 85.87]),
 ('Partitioned', [100.0, 100.0, 100.0, 100.0, 100.0, 100.0]),
 ('Low Affinity', [124.75, 96.61, 96.9, 9.53, 11.54, 88.44]),
 ('Change Affinity', [225.69, 142.15, 246.67, 37.76, 46.09, 100.51]),
 ('High Skew', [29.23, 17.97, 30.23, 2.22, 2.52, 12.79])]

# MP-Router throughput divided by each baseline in BASELINE_SYSTEMS.
target_over_baselines_x = [('Warmup', [49.31, 36.63, 32.67, 45.09, 22.24]),
 ('Partitioned', [33.92, 22.39, 24.88, 1.84, 1.41]),
 ('Low Affinity', [24.05, 20.5, 22.71, 17.09, 10.78]),
 ('Change Affinity', [15.11, 15.83, 10.14, 4.9, 3.07]),
 ('High Skew', [14.84, 15.94, 10.53, 10.62, 7.13])]

MISSING = []

WARNINGS = []
