# Auto-generated by extract_fig13_mlp.py.
# Do not edit by hand; rerun the extractor with the intended data directories.
#
# MP-Router baseline source: ../../../vldb_res/20260709000616(main)
# MLP source: ../../../vldb_res/20260716071500(mlp)

MLP_SYSTEMS = ['MP-Router with MLP', 'MP-Router']

mlp_data = [('0.1', [37240.65, 131878.1]),
 ('0.6', [27330.69, 128615.28]),
 ('0.8', [12315.89, 109656.54]),
 ('0.9', [6382.15, 91668.04]),
 ('1.1', [5060.43, 35430.12])]
