# Auto-generated by extract_fig12_key_page_map.py.
# Do not edit by hand; rerun the extractor with the intended data directory.
#
# Key-page-map source: /Users/hcy/Desktop/Ruc/论文投稿/SIGMOD 2026 MP-Router/vldb_res/20260709000616(main)

KP_SYSTEMS = ['PHR', 'PAR', 'CPR', 'MP-Router']

key_page_map_data = [('20%', [78605.88, 81289.73, 78076.17, 97991.87]),
 ('40%', [76992.33, 80551.1, 80550.4, 100642.33]),
 ('60%', [78915.5, 79686.9, 81059.43, 101555.47]),
 ('80%', [84946.67, 80488.73, 84666.1, 105710.27]),
 ('100%', [92646.87, 81121.17, 85782.47, 111648.73])]
