# Auto-generated by extract_fig14_ablation_breakdown.py.
# Do not edit by hand; rerun the extractor with the intended data directory.
#
# Main source: ../../../vldb_res/20260709000616(main)
# Ablation source: ../../../vldb_res/20260718190512(abaltion-new)
# Time-breakdown source: ../../../vldb_res/20260718190512(abaltion-new)

ABLATION_SYSTEMS = ['RR', 'w/o scheduling', 'w/o critical-path', 'w/o barrier', 'MP-Router']

ablation_data = [('0.1', [88175.43, 133107.0, 127372.79, 131923.43, 131878.1]),
 ('0.6', [84255.77, 124040.27, 122609.18, 128996.93, 128470.74]),
 ('0.8', [75974.53, 97935.9, 93343.98, 110861.27, 111192.79]),
 ('0.9', [15351.67, 15042.77, 79353.89, 14831.14, 94081.29]),
 ('1.1', [2798.0, 2873.17, 23230.9, 3520.57, 35430.12])]

time_breakdown_data = [('0.6',
  'Router Thread',
  [('Wait DB', 94.69), ('Wait Preprocess', 0.21), ('Conflict-Free', 2.66), ('Conflicting', 2.44)]),
 ('0.6', 'DB Connector', [('Wait Barrier', 0.21), ('Execute', 99.79)]),
 ('0.9',
  'Router Thread',
  [('Wait DB', 81.92), ('Wait Preprocess', 0.52), ('Conflict-Free', 2.02), ('Conflicting', 15.55)]),
 ('0.9', 'DB Connector', [('Wait Barrier', 5.93), ('Execute', 94.07)])]
