# Auto-generated by extract_fig5_cache_fusion_4kwr.py.
# Do not edit by hand; rerun the extractor with the intended data directory.
#
# Metric: cf_waits_per_kwr_business_txn
# SmallBank source: ../../../vldb_res/20260716160331(smallbank-4kwr)
# TPC-C source: ../../../vldb_res/20260716232528(tpcc-4kwr)

MAIN_SYSTEMS = ['RR', 'MWR', 'PHR', 'PAR', 'CPR', 'MP-Router']

CACHE_FUSION_METRIC = 'cf_waits_per_kwr_business_txn'

smallbank_cache_fusion_data = [('0.1', [2.776586, 2.621287, 1.926004, 2.327543, 1.934828, 1.553279]),
 ('0.6', [2.871423, 2.736569, 2.022981, 2.436376, 1.991777, 1.589269]),
 ('0.8', [3.313868, 3.181513, 2.38806, 2.956178, 2.35003, 1.871776]),
 ('0.9', [4.039119, 3.993727, 3.327248, 3.903396, 3.340616, 2.049291]),
 ('1.1', [6.828777, 6.970024, 6.133094, 6.719418, 6.026156, 1.920858])]

tpcc_cache_fusion_data = [('Normal', [30.045367, 30.152023, 27.572682, 28.537056, 27.197105, 5.590761]),
 ('50%', [30.639483, 29.829854, 28.389142, 29.830487, 28.27906, 6.752931]),
 ('80%', [31.77333, 31.284712, 29.172533, 31.572438, 28.119769, 7.449608]),
 ('90%', [32.079573, 32.167345, 29.375473, 32.105079, 28.087723, 6.340527])]

MISSING = []

WARNINGS = []
