# Auto-generated by extract_fig7_uniform_hotspot.py.
# Do not edit by hand; rerun the extractor with the intended data directory.
#
# Uniform-hotspot source: ../../../vldb_res/20260709000616(main)

MAIN_SYSTEMS = ['RR', 'MWR', 'PHR', 'PAR', 'CPR', 'MP-Router']

uniform_hotspot_data = [('100%', [88113.2, 88701.63, 110659.47, 101904.83, 102154.83, 130982.1]),
 ('10%', [84989.5, 86116.33, 106565.0, 99753.54, 99653.23, 126947.64]),
 ('1%', [67797.77, 69079.27, 83415.97, 76795.73, 84177.7, 98354.7]),
 ('0.1%', [59105.57, 56604.43, 68866.3, 60003.93, 58044.3, 74576.58])]
