# Auto-generated by extract_fig8_thread_scalability.py.
# Do not edit by hand; rerun the extractor with the intended data directory.
#
# Thread-scalability source: ../../../vldb_res/20260709000616(main)

MAIN_SYSTEMS = ['RR', 'MWR', 'PHR', 'PAR', 'CPR', 'MP-Router']

thread_scalability_data = [('2', [13685.1, 16720.37, 19293.03, 19557.37, 16514.67, 22439.7]),
 ('4', [25513.9, 28326.8, 35025.63, 32364.77, 30951.97, 40125.07]),
 ('8', [47094.37, 49635.23, 61644.2, 54383.2, 58249.77, 72551.43]),
 ('16', [75974.53, 76629.77, 90812.61, 82548.87, 83379.23, 109656.54]),
 ('24', [32116.43, 26992.23, 27614.51, 28960.3, 36629.62, 134123.66]),
 ('32', [24089.2, 21709.83, 22513.3, 20068.47, 26491.67, 129288.73])]
