# Auto-generated by extract_revision_data.py.
# Do not edit by hand; adjust CSV paths or extraction config instead.

MAIN_SYSTEMS = ['RR', 'MWR', 'PHR', 'PAR', 'CPR', 'MP-Router']

KP_SYSTEMS = ['PHR', 'PAR', 'CPR', 'MP-Router']

MLP_SYSTEMS = ['MP-Router with MLP', 'MP-Router']

ABLATION_SYSTEMS = ['MP-Router', 'w/o barrier', 'w/o critical-path', 'w/o scheduling']

throughput_zipfian_data = [('0.1', [83629.17, 84793.7, 106955.9, 96134.37, 97803.73, 126348.13]),
 ('0.6', [82187.26, 82718.88, 100301.26, 92793.34, 93070.26, 122045.9]),
 ('0.8', [72046.07, 72224.56, 84830.97, 68772.67, 78025.03, 107074.93]),
 ('0.9', [None, None, None, None, None, None]),
 ('1.1', [2611.65, 2475.33, 2642.91, 2682.67, 2654.77, 34410.69]),
 ('1.3', [1194.93, 1149.9, 1210.47, 1120.47, 1248.2, 19189.73])]

throughput_hotspot_data = [('100%', [83820.37, 85687.6, 105609.13, 96332.93, 93914.3, 126918.93]),
 ('10%', [81633.43, 82445.23, 102018.0, 94046.1, 91617.63, 121613.13]),
 ('1%', [66423.97, 67283.31, 80567.4, 74126.47, 77025.07, 94651.1]),
 ('0.1%', [56835.77, 56942.3, 65462.57, 57352.73, 64014.2, 72369.6])]

affinity_data = [('0%', [69158.63, 46215.8, 41845.33, 46077.07, 44887.64, 102658.0]),
 ('20%', [70295.83, 67901.37, 63878.2, 49267.33, 65056.4, 101074.2]),
 ('40%', [71193.87, 72548.82, 71343.1, 77485.9, 73654.11, 97253.69]),
 ('60%', [72234.57, 73524.1, 87638.0, 78653.24, 78679.07, 106994.43]),
 ('80%', [72046.07, 72224.56, 84830.97, 68772.67, 78025.03, 107074.93]),
 ('100%', [72827.43, 73148.37, 85625.13, 80289.07, 81315.23, 110117.23])]

thread_num_data = [('2', [13007.03, 15482.3, 17474.83, 17237.8, 15189.47, 20759.27]),
 ('4', [24280.77, 26650.5, 32401.73, 29904.73, 28825.9, 37935.17]),
 ('8', [43877.8, 45762.77, 55179.89, 51373.57, 54631.93, 66709.17]),
 ('16', [72046.07, 72224.56, 84830.97, 68772.67, 78025.03, 107074.93]),
 ('32', [19989.0, 18424.27, 22699.53, 18365.2, 24394.6, 117316.6]),
 ('64', [12793.8, 8117.33, 8402.0, 9652.77, 10390.7, 95532.68]),
 ('128', [5896.37, 5535.3, 5724.2, 6263.33, 6750.03, 96436.45])]

kp_data = [('20%', [76288.03, 75054.8, 77702.04, 93923.14]),
 ('40%', [76056.13, 76175.77, 77971.47, 94716.51]),
 ('60%', [76577.33, 76835.81, 78211.09, 98087.33]),
 ('80%', [81537.75, 77220.83, 78273.67, 101457.22]),
 ('100%', [89142.43, 79652.17, 81393.63, 107100.9])]

batch_size_data = [('10', [None]),
 ('100', [89347.49]),
 ('500', [102361.79]),
 ('1000', [107511.95]),
 ('5000', [105333.76]),
 ('10000', [107074.93]),
 ('50000', [112094.8]),
 ('100000', [116687.31])]

ablation_data = [('0.8', [107074.93, None, None, 93383.29]),
 ('0.9', [None, None, None, None]),
 ('1.1', [34410.69, None, None, 2274.39])]

mlp_data = [('0.1', [126047.3, 126348.13]),
 ('0.6', [119757.51, 122045.9]),
 ('0.8', [105917.87, 107074.93]),
 ('0.9', [None, None]),
 ('1.1', [33175.13, 34410.69]),
 ('1.3', [19550.03, 19189.73])]

TPCC_SYSTEMS = ['RR', 'MWR', 'PHR', 'PAR', 'CPR', 'MP-Router', 'Warehouse-aware']

tpcc_data = [('Unpartitioned', [757.77, 1041.57, 809.1, 1118.5, 1168.4, 7330.07, 19678.13]),
 ('Warehouse-partitioned', [10072.37, 10392.17, 10154.93, 11157.83, 10368.43, 9988.8, 51307.03])]

MISSING = ["throughput_zipfian/0.9/mode0: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': "
 "'0'}",
 "throughput_zipfian/0.9/mode25: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': "
 "'25'}",
 "throughput_zipfian/0.9/mode2: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': "
 "'2'}",
 "throughput_zipfian/0.9/mode23: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': "
 "'23'}",
 "throughput_zipfian/0.9/mode28: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': "
 "'28'}",
 "throughput_zipfian/0.9/mode11: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': "
 "'11'}",
 "batch_size/10/mode11: {'scan_axis': 'batch_size', 'batch_size': '10', 'run_mode': '11'}",
 "ablation/0.8/mode26: {'scan_axis': 'base', 'access_pattern': '1', 'zipfian_theta': '0.8', 'run_mode': '26'}",
 "ablation/0.8/mode30: {'scan_axis': 'base', 'access_pattern': '1', 'zipfian_theta': '0.8', 'run_mode': '30'}",
 "ablation/0.9/mode11: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': '11'}",
 "ablation/0.9/mode26: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': '26'}",
 "ablation/0.9/mode30: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': '30'}",
 "ablation/0.9/mode13: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': '13'}",
 "ablation/1.1/mode26: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '1.1', 'run_mode': '26'}",
 "ablation/1.1/mode30: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '1.1', 'run_mode': '30'}",
 "mlp/0.9/mlp: {'scan_axis': 'mlp_zipfian', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': '11', "
 "'mlp_enabled': '1'}",
 "mlp/0.9/baseline: {'scan_axis': 'access', 'access_pattern': '1', 'zipfian_theta': '0.9', 'run_mode': '11', "
 "'mlp_enabled': '0'}"]
